import { G, Shape, Svg } from '@svgdotjs/svg.js';
import { IFigureAnimation, IFigureAppearanceConfig, IGraphConfig, XY } from '../pidraw.common';
import { Label } from '../labels/Label';
export declare abstract class AbstractFigure {
    constructor(rootSVG: Svg, name: string);
    protected _rootSVG: Svg;
    get rootSVG(): Svg;
    protected _name: string;
    get name(): string;
    protected _element: G;
    get element(): G;
    protected _shape: Shape;
    get shape(): Shape;
    set shape(value: Shape);
    protected _appearance: IFigureAppearanceConfig;
    get appearance(): IFigureAppearanceConfig;
    set appearance(value: IFigureAppearanceConfig);
    protected _static: boolean;
    get static(): boolean;
    set static(value: boolean);
    protected _isDraggable: boolean;
    get isDraggable(): boolean;
    set isDraggable(value: boolean);
    protected _label: Label | null;
    get label(): Label | null;
    protected _animate: IFigureAnimation | null;
    get animate(): IFigureAnimation | null;
    set animate(value: IFigureAnimation | null);
    get graphConfig(): IGraphConfig;
    abstract computed(): this;
    hide(): this;
    show(): this;
    strokeable(): Shape[];
    fillable(): Shape[];
    fill(color?: string): this;
    stroke(): this;
    stroke(color: string): this;
    stroke(strokeWidth: number): this;
    stroke(color: string, strokeWidth: number): this;
    dash(dasharray?: string): this;
    dot(): this;
    clear(all?: boolean): this;
    update(forceUpdate?: boolean): this;
    addLabel(text?: string, asHtml?: boolean, texConverter?: (value: string) => string): Label;
    abstract moveLabel(): this;
    updateLabel(): this;
    computeLabel(): string;
    move(pos: number): this;
    move(pos: XY): this;
    scale(value: XY | number): this;
    mark(value?: string | boolean, options?: (string | number)[]): this;
    follow(x: number, y: number): XY;
}
